---
- name: download archives
  become: true
  become_user: "{{ syncthing_user }}"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ syncthing_app_path }}/{{ item.file }}"
  with_items:
    - url: "{{ syncthing_url }}"
      file: "{{ syncthing_archive }}"
    - url: "{{ syncthing_inotify_url }}"
      file: "{{ syncthing_inotify_archive }}"

- name: extract archives
  unarchive:
    src: "{{ syncthing_app_path }}/{{ item }}"
    dest: "{{ syncthing_app_path }}"
    copy: no
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
  with_items:
    - "{{ syncthing_archive }}"
    - "{{ syncthing_inotify_archive }}"

- name: link version
  file:
    state: link
    path: "{{ syncthing_app_path }}/latest"
    src: "{{ syncthing_app_path }}/{{ syncthing_extraced_dir }}"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
  notify:
    - start services

