---

- name: create user
  sudo: true
  when: syncthing_user_create == true
  user:
    name: "{{ syncthing_user }}"
    createhome: yes
    state: present
    system: yes

- name: create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
  with_items:
    - "{{ syncthing_app_path }}"
    - "{{ syncthing_config_path }}"
    - "{{ syncthing_data_path }}"

- name: fetch syncthing metadata
  uri:
      url: https://api.github.com/repos/syncthing/syncthing/releases/latest
      return_content: yes
      body_format: json
  register: syncthing_github

- name: fetch syncthing_inotify metadata
  uri:
      url: https://api.github.com/repos/syncthing/syncthing-inotify/releases/latest
      return_content: yes
      body_format: json
  register: syncthing_inotify_github

- set_fact:
    syncthing_version: "{{ syncthing_github.json.tag_name }}"
    syncthing_inotify_version: "{{ syncthing_inotify_github.json.tag_name }}"

- set_fact:
    syncthing_extraced_dir: "syncthing-linux-{{ syncthing_arch }}-{{ syncthing_version }}"
    syncthing_inotify_extraced_dir: "syncthing-inotify-linux-{{ syncthing_arch }}-{{ syncthing_inotify_version }}"

- set_fact:
    syncthing_archive: "{{ syncthing_extraced_dir }}.tar.gz"
    syncthing_inotify_archive: "{{ syncthing_inotify_extraced_dir }}.tar.gz"

- set_fact:
    syncthing_url: "https://github.com/syncthing/syncthing/releases/download/{{ syncthing_version }}/{{ syncthing_archive }}"
    syncthing_inotify_url: "https://github.com/syncthing/syncthing-inotify/releases/download/{{ syncthing_inotify_version }}/{{ syncthing_inotify_archive }}"

- name: download archives
  become: true
  become_user: "{{ syncthing_user }}"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ syncthing_app_path }}/{{ item.file }}"
  with_items:
    - url: "{{ syncthing_url }}"
      file: "{{ syncthing_archive }}"
    - url: "{{ syncthing_inotify_url }}"
      file: "{{ syncthing_inotify_archive }}"

- name: extract archives
  unarchive:
    src: "{{ syncthing_app_path }}/{{ item }}"
    dest: "{{ syncthing_app_path }}"
    copy: no
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
  with_items:
    - "{{ syncthing_archive }}"
    - "{{ syncthing_inotify_archive }}"

- name: link version
  file:
    state: link
    path: "{{ syncthing_app_path }}/latest"
    src: "{{ syncthing_app_path }}/{{ syncthing_extraced_dir }}"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"

- name: generate starup script
  template:
    src: "{{ item }}.j2"
    dest: "{{ syncthing_app_path }}/{{ item }}"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
    mode: 0755
    validate: "bash -n %s"
  with_items:
    - syncthing.sh
    - syncthing-inotify.sh

- name: create config file
  become: true
  become_user: "{{ syncthing_user }}"
  command: >
    "{{ syncthing_app_path }}/latest/syncthing"
    "-generate={{ syncthing_config_path }}"
  args:
    creates: "{{ syncthing_config_path }}/config.xml"

- name: enable gui
  xml:
    file: "{{ syncthing_config_path }}/config.xml"
    xpath: "/configuration/gui/address"
    value: "{{ syncthing_gui_address }}"

- name: disable auto update
  xml:
    file: "{{ syncthing_config_path }}/config.xml"
    xpath: "/configuration/options/autoUpgradeIntervalH"
    value: "0"

- name: generate systemd services
  template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items:
    - syncthing
    - syncthing-inotify

- name: setup services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - syncthing
    - syncthing-inotify

